CREATE TABLE Contents.tblArtistAlbums (
	albumID INT IDENTITY(1,1) NOT NULL,
	albumName VARCHAR(255) NOT NULL,
	genreName VARCHAR(255) NOT NULL,
	dateOfRelease DATE NOT NULL,
	formatID INT NOT NULL,
	artistID INT NOT NULL,
	roomID INT NOT NULL,
	shelfTag VARCHAR(1) NOT NULL,
	shelfRow VARCHAR(2) NOT NULL,
	lost BIT NOT NULL

	FOREIGN KEY (formatID) REFERENCES Properties.tblFormat (formatID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY (artistID) REFERENCES Contents.tblArtists (artistID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY (roomID) REFERENCES Properties.tblStorageRoom (roomID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY (shelfTag) REFERENCES Properties.tblShelf (shelfTag) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY (shelfRow) REFERENCES Properties.tblRow (shelfRow) ON DELETE NO ACTION ON UPDATE NO ACTION
	
);


CREATE TABLE Contents.tblBandAlbums (
	albumID INT IDENTITY(1,1) NOT NULL,
	albumName VARCHAR(255) NOT NULL,
	genreName VARCHAR(255) NOT NULL,
	dateOfRelease DATE NOT NULL,
	formatID INT NOT NULL,
	bandID INT NOT NULL,
	roomID INT NOT NULL,
	shelfTag VARCHAR(1) NOT NULL,
	shelfRow VARCHAR(2) NOT NULL,
	lost BIT NOT NULL

	FOREIGN KEY (formatID) REFERENCES Properties.tblFormat (formatID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY (bandID) REFERENCES Contents.tblBands (bandID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY (roomID) REFERENCES Properties.tblStorageRoom (roomID) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY (shelfTag) REFERENCES Properties.tblShelf (shelfTag) ON DELETE NO ACTION ON UPDATE NO ACTION,
	FOREIGN KEY (shelfRow) REFERENCES Properties.tblRow (shelfRow) ON DELETE NO ACTION ON UPDATE NO ACTION
	
);
